// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtakjfxyvnanltsztbqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YWtqZnh5dm5hbmx0c3p0YnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTQzMzAsImV4cCI6MjA2MjUzMDMzMH0.gp50Q-8EBZPAlDebj_DVuC5l6nH_h7EGxGj54yX8rgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);